st
zero
balance

dretime

st
balance
dfraig
dc2 -b -p
drw -z
drf -z
retime -M 5 -D 1 -o

st
balance
dfraig
dc2 -b -p
drw -z
drf -z
retime -M 5 -D 1 -o

st
balance
dfraig
dc2 -b -p
drw -z
drf -z
retime -M 5 -D 1 -o


st
balance
dfraig
dc2 -b -p
drw -z
drf -z
retime -M 5 -D 1 -o

st
balance
dfraig
dc2 -b -p
drw -z
balance
dfraig
dc2 -b -p
drw -z
balance

scleanup

map -D 1

echo ABCSTATS
print_stats